version : '3'

services:
  php:
    container_name: "longpoll_chat_php"
    image: "php:7.2-fpm"
    volumes:
      - "..:/var/www/longpolling"

  nginx:
    container_name: "longpoll_chat_nginx"
    build:
      context: ./nginx
    ports:
      - "80:80"
    links:
      - "php"
    volumes:
    - "..:/var/www/longpolling"